//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class projectDataConnections : DbContext
    {
        public projectDataConnections()
            : base("name=projectDataConnections")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<companyCustomer> companyCustomer { get; set; }
        public virtual DbSet<companyPerformer> companyPerformer { get; set; }
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<project> project { get; set; }
        public virtual DbSet<projectManager> projectManager { get; set; }
    }
}
