//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public project()
        {
            this.employee = new HashSet<employee>();
        }
    
        public int projID { get; set; }
        public string name { get; set; }
        public System.DateTime dateStart { get; set; }
        public System.DateTime dateFinish { get; set; }
        public int priority { get; set; }
        public string comment { get; set; }
        public int id_projM { get; set; }
        public int id_comP { get; set; }
        public int id_comC { get; set; }
    
        public virtual companyCustomer companyCustomer { get; set; }
        public virtual companyPerformer companyPerformer { get; set; }
        public virtual projectManager projectManager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee> employee { get; set; }
    }
}
